name: afk-plugin
version: '1.0-SNAPSHOT'
main: io.key.afkPlugin.enderpearlStasis
api-version: '1.21'
authors: [rhea80]
description: A plugin to toggle spectator mode when typing /afk.
commands:
  afk:
    description: Puts user into Spectator mode. Use again to get out of spectator mode.
    usage: /afk
