name: afk
version: '1.0-SNAPSHOT'
main: io.key.afkPlugin.enderpearlStasis
api-version: '1.21'
authors: [rhea80]
description: A plugin to toggle spectator mode when typing /afk.
commands:
  afk:
    description: afk's a player.
    usage: /afk
